# Generated by Django 3.2.16 on 2022-11-07 10:40

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_admin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=backend.models.category_path)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(upload_to=backend.models.user_path),
        ),
    ]
