# Generated by Django 3.2.16 on 2022-11-08 09:09

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20221108_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=25)),
                ('stork', models.IntegerField(default=0)),
                ('shortdesc', models.TextField()),
                ('productdesc', models.TextField()),
                ('featureimage', models.ImageField(default='default.jpg', upload_to=backend.models.product_path)),
                ('galleryimage', models.ImageField(default='default.jpg', upload_to=backend.models.product_path)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subcategory')),
            ],
        ),
    ]
