# Generated by Django 3.2.16 on 2022-11-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stork',
            new_name='stock',
        ),
    ]
