# Generated by Django 3.2.16 on 2022-11-08 20:43

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_product_featureimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='galleryimage',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, default='BDT', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortdesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=backend.models.product_path)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
        ),
    ]
