# Generated by Django 3.2.16 on 2022-11-09 05:26

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20221109_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default=None, upload_to=backend.models.product_path),
        ),
    ]
