# Generated by Django 3.2.16 on 2022-11-09 11:41

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('site_logo', models.ImageField(upload_to=backend.models.settings_path)),
                ('hero_image', models.ImageField(upload_to=backend.models.settings_path)),
            ],
        ),
    ]
