# Generated by Django 3.2.16 on 2022-11-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
