# Generated by Django 3.2.16 on 2022-11-09 13:27

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_setting_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_us',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='about_us_img',
            field=models.ImageField(default=None, upload_to=backend.models.settings_path),
        ),
        migrations.AddField(
            model_name='settings',
            name='future_focused',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='future_forused_img',
            field=models.ImageField(default=None, upload_to=backend.models.settings_path),
        ),
        migrations.AddField(
            model_name='settings',
            name='who_we',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='who_we_image',
            field=models.ImageField(default=None, upload_to=backend.models.settings_path),
        ),
    ]
