# Generated by Django 3.2.16 on 2022-11-09 13:36

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_settings_about_us_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about_us',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='future_focused',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='future_forused_img',
            field=models.ImageField(upload_to=backend.models.settings_path),
        ),
        migrations.AlterField(
            model_name='settings',
            name='who_we',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='who_we_image',
            field=models.ImageField(upload_to=backend.models.settings_path),
        ),
    ]
