# Generated by Django 3.2.16 on 2022-11-09 15:01

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20221109_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, upload_to=backend.models.user_path),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
